# Generated by Django 5.1.6 on 2025-02-28 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.TextField(default='https://us.123rf.com/450wm/rashadashurov/rashadashurov2002/rashadashurov200201094/140529504-icono-de-foto-en-blanco.jpg?ver=6')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FrutaCategoria', to='Frutas.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FrutaProveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
